name: Unity Build and Test
run-name: Checking if Unity project builds correctly in ${{ github.ref }} branch
on: 
   pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  BuildUnityProject:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         token: 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
         submodules: recursive
         fetch-depth: 0
         lfs: true

      - name: Find Comment
        if: always()
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Unity build status
          
      - name: Create or update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Unity build status: 
            Working ⚙
          edit-mode: replace
          
#########################################################################################
        
      - name: Restore LFS cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-
                              
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
     
#########################################################################################
          
      - name: Set success output
        if: success()
        run: echo "actionStatus=Unity project builded successfully good job!" >> $GITHUB_ENV
        
      - name: Set failure output
        if: failure()
        run: echo "actionStatus=Unity project failed to build, read action workflow for more detailed info." >> $GITHUB_ENV
      
      - name: Find Comment
        if: always()
        uses: peter-evans/find-comment@v2
        id: findComment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Unity build status

      - name: Update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Unity build status: 
            ${{env.actionStatus}}
          edit-mode: replace