name: Unity Build
run-name: Checking if Unity project builds correctly in ${{ github.ref }} branch.
on: 
   pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  BuildUnityProject:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         token: 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
         submodules: true
         
      - name: Create Body File
        run: echo $'Unity build status:\nWorking ⚙' > BodyFile.txt

      - name: Find comment
        if: always()
        uses: peter-evans/find-comment@v2
        id: findComment
        with:
           issue-number: ${{ github.event.pull_request.number }}
           comment-author: 'github-actions[bot]'
           body-includes: Unity build status    
           
      - name: Create or update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
           comment-id: ${{ steps.findComment.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
           body-file: 'BodyFile.txt'
           edit-mode: replace  
          
#########################################################################################
        
      - uses: actions/cache@v3
        with:
         path: Library
         key: Library-StandaloneWindows64
         restore-keys: Library-
         
      ###########################
      #  Set Scripting Backend  #
      ###########################
      
      - name: Set Scripting Backend To il2cpp
        run: |
          sudo mv "./ProjectSettings/ProjectSettings-MONO.asset" "./ProjectSettings/ProjectSettings.asset"
                              
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
            targetPlatform: StandaloneWindows64
            allowDirtyBuild: true
            
      - uses: actions/upload-artifact@v2
        with:
         name: Build
         path: build
     
#########################################################################################
          
      - name: Set success output
        if: success()
        run: echo $'Unity build status:\nSuccess!\nThere were no problems with building unity project' > BodyFile.txt
        
      - name: Set failure output
        if: failure()
        run: echo $'Unity build status:\nFailed\n Read action details for more informations' > BodyFile.txt
      
      - name: Find comment
        if: always()
        uses: peter-evans/find-comment@v2
        id: fc
        with:
           issue-number: ${{ github.event.pull_request.number }}
           comment-author: 'github-actions[bot]'
           body-includes: Unity build status     
        
      - name: Create or update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
           comment-id: ${{ steps.fc.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
           body-file: 'BodyFile.txt'
           edit-mode: replace
