# checks if files are in specific folders or subfolders of these folders
# for example:
# - animation controllers in Art/Animations
# - FBX files in Art/FBXs
# - materials in Art/Materials
# - shader graph files ???
# - textures (.png files) in Art/Textures

name: Check Files Path
run-name: Checking if files are in correct folder in ${{ github.ref }} branch
# each time pull request is commited to we run this script
on: 
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:        
  CheckFilesPathAndPrintComment:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Body File
      run: |
        echo $'Files path check status:\nWorking ⚙' > BodyFile.txt
        
    - name: Find comment
      if: always()
      uses: peter-evans/find-comment@v2
      id: findComment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Files path check status      
        
    - name: Create or update comment
      if: always()
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.findComment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-file: 'BodyFile.txt'
        edit-mode: replace         

    - name: Check files path
      run: chmod +x ./.github/scripts/files-with-wrong-path.sh && ./.github/scripts/files-with-wrong-path.sh false
          
    - name: Find comment
      if: always()
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Files path check status     
        
    - name: Create or update comment
      if: always()
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-file: 'BodyFile.txt'
        edit-mode: replace 
