name: Check Files Name
run-name: Checking if files are named with pascal case in ${{ github.ref }} branch
on: 
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:        
  CheckFilesNameAndPrintComment:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Body File
      run: |
        echo $'Files name check status:\nWorking ⚙' > BodyFile.txt
        
    - name: Find comment
      if: always()
      uses: peter-evans/find-comment@v2
      id: findComment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Files name check status     
        
    - name: Create or update comment
      if: always()
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.findComment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-file: 'BodyFile.txt'
        edit-mode: replace          

    - name: Check Files Name
      run: chmod +x ./.github/scripts/files-with-wrong-name.sh && ./.github/scripts/files-with-wrong-name.sh false

    - name: Find comment
      if: always()
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Files name check status     
        
    - name: Create or update comment
      if: always()
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-file: 'BodyFile.txt'
        edit-mode: replace 
