name: Slack Notification

on:
  push:
    branches:
      - main
      - master

jobs:
  NotifySlackChannel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Send message on slack channel
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: Please update your branches.
        SLACK_TITLE: Has been merged to main branch!
        SLACK_USERNAME: Notify-Merge-Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
