name: Weekly Repository Cleanup

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 0'

jobs:
  CleanRepository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clear branches withouth commits since 2 weeks
      run: chmod +x ./.github/scripts/branch-cleanup.sh && ./.github/scripts/branch-cleanup.sh false

    - name: Clear all caches
      uses: actions/github-script@v6
      with:
        script: |
          const caches = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          for (const cache of caches.data.actions_caches) {
            console.log(cache)
            github.rest.actions.deleteActionsCacheById({
              owner: context.repo.owner,
              repo: context.repo.repo,
              cache_id: cache.id,
            })
          }

    - name: Clear 7 days old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days'